# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625d009234016b9903ae9a809e317a609ee519ad587c17f234531c1d4360f3a910acd8c777058b3df266b185ebbaa45ba983139591b49ad350daa929fb793032

test:
  secret_key_base: fc1eaad4a173b4c4138b7b0b2fc79c2076796c2bbb58e4ef6627c1c4453ff0f65c312223ac6d5d2fb66330a1872e293897c5b378fa1f9211afca66d3b0820435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
